apiVersion: v1
kind: ConfigMap
metadata:
  name: ddd-sales-config
  namespace: default
  labels:
    app: ddd-sales-api
data:
  jwt-issuer: "DDD.Sales.API"
  jwt-audience: "DDD.Sales.Client"
  serilog-min-level: "Information"
  rate-limit-window: "1"
  rate-limit-permit-limit: "100"

  # OpenTelemetry
  opentelemetry-otlp-endpoint: "http://jaeger:4317"

  # External Services
  payment-gateway-url: "https://api.payment-gateway.com"

  # RabbitMQ/MassTransit
  rabbitmq-host: "rabbitmq"
  rabbitmq-port: "5672"
  rabbitmq-vhost: "/"
