apiVersion: v1
kind: ConfigMap
metadata:
  name: cleanarchitecture-config
data:
  database-provider: "SqlServer"
  jwt-issuer: "CleanArchitectureAPI"
  jwt-audience: "CleanArchitectureClient"
  aspnetcore-environment: "Production"
